### ISSUE TITLE
Questions regarding the datasets

### ISSUE THREAD

**Issue by Nate1874** [AllenCellModeling/torch_integrated_cell#3]
I recently read your paper and code, but I do have some confusions regarding how to deal with the data.

1. Take images in Alpha actinin folder as example, can you explain the meaning of different suffix in file name? Such as 'flat', 'flat_cb', 'proj', 'proj_cb'.
![image](https://user-images.githubusercontent.com/20103218/26904532-331448d6-4b97-11e7-9342-df449080815f.png)

2. In your data_reader and imtools files, it looks like the image will be scaled to 256 by 256 and opts.image_sub_size is used to reshape the image from 753 by 753 to 256 by 256. However, some images are 1050*1050 (name end with 'proj' and 'proj_cb'), will these images be used? I did not see any code deal with these larger images.

Could you explain a little to help me have a better understanding?   Thanks a lot.

**Comment by gregjohnso** [comment]
It looks like we dumped images that we were not using into the data collection. We will fix that, but in the mean time you can remove all files except the ones that end with *.ome.tif_flat.png.

**Comment by donovanr** [comment]
We've removed the extra images that the model wasn't looking at.  There should be 6077 images in the S3 bucket now (in total, in the ten subdirectories).
