### ISSUE TITLE
How to separate reference and structure channels

### ISSUE THREAD

**Issue by Nate1874** [AllenCellModeling/torch_integrated_cell#4]
In your paper, it is mentioned "We first train the model of cell and nuclear shape variation"  and then "then train the conditional model".  For the the model of cell and nuclear shape variation, only X<sup>r</sup> is used and for second part, both X<sup>r</sup>  , X<sup>s</sup> will be used. 

In your data, all channels are included in one image. How do you separate the r channel for the first part of training? I cannot find related code for it.  Could you help with this? 

Thanks.

**Comment by gregjohnso** [comment]
In DataProvider2D there are two parameters of the options structure:
`opts.channel_inds_in` 
`opts.channel_inds_out` 
These tell the DataProvider which channels (RGB in that order) to return when asking for data.

These parameters are set in the call to `model_opts = setup.getModelOpts()` on line 106 in train_model_2D.lua for the first reference structure model and on line 189 of train_model_2D.lua for the conditional model.
