### ISSUE TITLE
What's the maximum likelihood  structure localization function used in the paper?

### ISSUE THREAD

**Issue by Nate1874** [AllenCellModeling/torch_integrated_cell#6]
In your paper, algorithm 3.  The Z<sup>s</sup> is chosen by the argmax function of p(z<sub>s</sub>). What kind of p(z<sub>s</sub>) is used? I cannot find such code in your work, could you help to point it out?

Thanks.

**Comment by gregjohnso** [comment]
In the paper we model the latent distribution of structure, z^s, with a normal distribution of N(0,1). Therefore the argmax of p(z_s) is therefore a vector of zeros.
